#!/usr/bin/env python3
"""Build a screen's Layout node from the manifest's positions (D-77).

Scenes own position once they exist, so this is a scaffold, not a sync: it refuses to
touch a scene whose Layout it did not write, and after the first run the .tscn is the
truth and the manifest's `layout` field is dead weight for that screen.

Each slot becomes a Sprite2D when its art is present -- so the 2D editor shows the real
thing -- and a ColorRect when it is not. Chrome ships at 2x (D-76) and is scaled to half
so it sits at its slot's size. Guides are hidden at load by SceneLayout.

    python3 tools/dev/scenes.py            # report what each screen would get
    python3 tools/dev/scenes.py --write    # write the Layout blocks
"""
import json
import pathlib
import re
import struct
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SCENES = ROOT / "game" / "scenes"
MARK = "; generated by tools/dev/scenes.py -- positions here are the truth from now on (D-77)"

# Which manifest screen each scene draws, and an example entry for the slots a screen
# fills from content at runtime (a portrait differs per founder; the editor shows one).
SCREENS = {
    "Build": "build",
    "Battle": "battle",
    "Autopsy": "autopsy",
}


def png_size(path):
    with path.open("rb") as f:
        head = f.read(24)
    return struct.unpack(">II", head[16:24])


def short(entry_id, taken):
    """`ui.build.firm_panel` -> `firm_panel`, widening only when that collides."""
    parts = entry_id.split(".")
    for n in range(1, len(parts) + 1):
        name = "_".join(parts[-n:])
        if name not in taken:
            return name
    return entry_id.replace(".", "_")


def slots(entries, screen):
    out = []
    taken = set()
    for e in entries:
        if screen not in e["screens"] or "layout" not in e:
            continue
        name = short(e["id"], taken)
        taken.add(name)
        out.append((name, e))
    return out


def node(name, e):
    w, h = e["sprite"]["w"], e["sprite"]["h"]
    # A layout point is where the anchor sits, not the top-left; a scene node is placed by
    # its top-left, so bake the anchor in once here rather than at every draw.
    a = e["sprite"]["anchor"]
    x = int(round(e["layout"]["x"] - a["x"] * w))
    y = int(round(e["layout"]["y"] - a["y"] * h))
    asset = ROOT / e["sprite"]["asset"]
    if asset.is_file():
        fw, _ = png_size(asset)
        scale = w / fw if fw else 1
        res = "res://" + e["sprite"]["asset"].split("game/", 1)[1]
        return res, (f'[node name="{name}" type="Sprite2D" parent="Layout"]\n'
                     f'position = Vector2({x}, {y})\n'
                     f'centered = false\n'
                     + (f'scale = Vector2({scale}, {scale})\n' if scale != 1 else '')
                     + 'texture = ExtResource("{ref}")\n')
    return None, (f'[node name="{name}" type="ColorRect" parent="Layout"]\n'
                  f'offset_left = {float(x)}\noffset_top = {float(y)}\n'
                  f'offset_right = {float(x + w)}\noffset_bottom = {float(y + h)}\n'
                  f'color = Color(0.85, 0.8, 0.65, 0.2)\n')


def main():
    write = "--write" in sys.argv
    entries = json.loads((ROOT / "manifest" / "sprites.json").read_text(encoding="utf-8"))["entries"]
    for scene_name, screen in SCREENS.items():
        path = SCENES / f"{scene_name}.tscn"
        text = path.read_text(encoding="utf-8")
        if "[node name=\"Layout\"" in text:
            print(f"{scene_name}: already has a Layout; it is the truth now, refusing to overwrite it")
            continue
        found = slots(entries, screen)
        print(f"{scene_name}: {len(found)} slots -> {', '.join(n for n, _ in found)}")
        if not write:
            continue

        head = text.split("\n[node name=\"Layout\"")[0].rstrip("\n")
        ext, body, next_id = [], [], 2
        for name, e in found:
            res, block = node(name, e)
            if res is not None:
                ref = str(next_id)
                ext.append(f'[ext_resource type="Texture2D" path="{res}" id="{ref}"]')
                block = block.replace("{ref}", ref)
                next_id += 1
            body.append(block)

        # .tscn order is strict: the header, then every ext_resource, then every node.
        lines = [l for l in head.split("\n") if l.strip()]
        header = re.sub(r"load_steps=\d+", f"load_steps={len(ext) + 2}", lines[0])
        existing = [l for l in lines[1:] if l.startswith("[ext_resource")]
        nodes = [l for l in lines[1:] if not l.startswith("[ext_resource")]
        out = "\n".join([header, ""] + existing + ext + [""] + nodes + ["", MARK,
                        '[node name="Layout" type="Node2D" parent="."]', ""] + body)
        path.write_text(out, encoding="utf-8", newline="\n")
        print(f"  wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
