#!/usr/bin/env python3
"""The ranked art worklist (ART_PIPELINE.md §7.3) and the folder tree the art goes into.

    python3 tools/dev/worklist.py            # writes docs/ART_WORKLIST.md and creates every asset folder
    python3 tools/dev/worklist.py --tier 1   # only the most visible tier in the sheet (folders are always all made)

For every manifest entry without art it prints one row: rank, id, the exact file to create (path and
pixel size), anchor, footprint, frames if any, and what the slot has to read as. Rank = visibility tier,
then how many screens the entry is on, then kind, then id (§7.3). Drop a PNG at the path at the exact size
and the game uses it; `validate-manifest` rejects a wrong size and updates the coverage numbers.
"""
import argparse
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
KIND_ORDER = ["employee", "tile", "furniture", "ui", "icon", "fx", "background", "font"]
ANCHORS = {(0.0, 0.0): "top-left", (0.5, 0.0): "top-centre", (0.5, 1.0): "bottom-centre", (0.5, 0.5): "centre", (0.0, 1.0): "bottom-left", (1.0, 1.0): "bottom-right"}


def anchor_name(a):
    return ANCHORS.get((a["x"], a["y"]), f"({a['x']}, {a['y']})")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tier", type=int, default=None, help="only this visibility tier in the sheet")
    args = ap.parse_args()
    manifest = json.load(open(os.path.join(ROOT, "manifest", "sprites.json")))
    entries = manifest["entries"]
    folders = set()
    for e in entries:
        folders.add(os.path.dirname(os.path.join(ROOT, e["sprite"]["asset"])))
    for d in sorted(folders):
        os.makedirs(d, exist_ok=True)
        keep = os.path.join(d, ".gitkeep")
        if not os.listdir(d):
            open(keep, "w").close()

    def rank(e):
        return (e["visibility"], -len(e["screens"]), KIND_ORDER.index(e["kind"]) if e["kind"] in KIND_ORDER else 99, e["id"])

    todo = []
    for e in sorted(entries, key=rank):
        path = os.path.join(ROOT, e["sprite"]["asset"])
        if e["kind"] == "font" or os.path.exists(path):
            continue
        if args.tier is not None and e["visibility"] != args.tier:
            continue
        todo.append(e)

    lines = [
        "# Art worklist",
        "",
        "Generated by `python3 tools/dev/worklist.py` from `manifest/sprites.json`; do not edit. One row per slot",
        "without art, most visible first (ART_PIPELINE.md §7.3). Create the file at the exact path and size and the",
        "game uses it in place of the placeholder; `dotnet run --project src/CompanyWars.Tools -- validate-manifest`",
        "rejects a wrong size. Paths are relative to the repository root. Anchor is the point the layout places.",
        "",
        f"{len(todo)} slots without art of {len(entries)}.",
        "",
        "| # | Slot | File | Size | Anchor | Footprint | Frames | Screens | Reads as | Candidate source |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for i, e in enumerate(todo, 1):
        s = e["sprite"]
        fp = e.get("footprint")
        frames = s.get("frames") or {}
        frame_text = ", ".join(f"{k} ×{v[2] if len(v) > 2 else 1}" for k, v in frames.items()) if frames else "—"
        lines.append("| {} | `{}` | `{}` | {}×{} | {} | {} | {} | {} | {} | {} |".format(
            i, e["id"], s["asset"], s["w"], s["h"], anchor_name(s["anchor"]),
            f"{fp['w']}x{fp['h']}" if fp else "—", frame_text, ", ".join(e["screens"]),
            e.get("reads", "").replace("|", "/"), (e.get("candidateSource") or e.get("candidate") or "").replace("|", "/")))
    out = os.path.join(ROOT, "docs", "ART_WORKLIST.md")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote docs/ART_WORKLIST.md: {len(todo)} slots without art; {len(folders)} folders under game/assets/")


if __name__ == "__main__":
    main()
